name: Сборка и Компиляция Карт
on:
  push:
    branches: [beta-dev]
    paths:
      - '_maps/**'
  pull_request:
    branches: [beta-dev]
    paths:
      - '_maps/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile_all_maps:
    name: Compile Maps
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup cache
        id: cache-byond
        uses: actions/cache@v3
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-byond-cache-${{ secrets.CACHE_PURGE_KEY }}-${{ hashFiles('dependencies.sh') }}-${{ hashFiles('.github/workflows/ci_suite.yml') }}
      - name: Install BYOND
        if: steps.cache-byond.outputs.cache-hit != 'true'
        run: bash tools/ci/install_byond.sh

      - name: Compile All Maps
        run: |
          source $HOME/BYOND/byond/bin/byondsetup
          tools/build/build --ci dm -DCIBUILDING -DCITESTING -DALL_MAPS -DFULL_INIT
